// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bank.Model;

#nullable disable

namespace bank.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20261004121128_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("bank.Model.Bank", b =>
                {
                    b.Property<int>("bankid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bankid"));

                    b.Property<string>("bankbranch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bankname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("bankpin")
                        .HasColumnType("int");

                    b.Property<string>("banktype")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("bankid");

                    b.ToTable("bank");
                });
#pragma warning restore 612, 618
        }
    }
}
